- name: restart libvirtd
  become: yes
  service:
    name: libvirtd
    state: restarted
    enabled: yes
  listen:
    - restart firewalld
    - reload firewalld

- name: reload systemd unit files
  become: yes
  systemd:
    daemon_reload: yes
