- name: install NFS server
  apt:
    package:
      - nfs-kernel-server
      - nfs-common
    state: present

- name: configure NFS exports
  template:
    src: etc_exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: restart nfs-kernel-server
