# @tag homepage-extra-icons - install additional icons for the nodiscc.xsrv.homepage role

galaxy_info:
  role_name: homepage_extra_icons
  author: "nodiscc <nodiscc@gmail.com>"
  description: "additional icons for the nodiscc.xsrv.homepage role"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
        - 11
        - 12
  galaxy_tags:
    - homepage

dependencies: []
