- name: import variable checks tasks
  import_tasks: checks.yml
  tags:
    - prometheus
    - checks

- name: import prometheus installation tasks
  become: yes
  import_tasks: prometheus.yml
  tags: prometheus
