- name: enable required apache modules
  command: a2enmod {{ item }}
  with_items:
    - headers
    - proxy
    - proxy_http
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"

- name: copy awesome-selfhosted apache virtualhost configuration
  template:
    src: etc_apache2_sites-available_awesome-selfhosted.conf.j2
    dest: /etc/apache2/sites-available/awesome-selfhosted.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload apache

- name: enable awesome-selfhosted apache virtualhost configuration
  command: a2ensite awesome-selfhosted
  args:
    creates: "/etc/apache2/sites-enabled/awesome-selfhosted.conf"
  notify: reload apache

- name: add a hosts file entry for the awesome-selfhosted server fqdn
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1	{{ awesome_selfhosted_html_fqdn }}' # noqa no-tabs
    state: present
