- name: setup firewalld rules for znc
  ansible.posix.firewalld:
    zone: "{{ item.zone }}"
    service: ircs
    state: "{{ item.state }}"
    permanent: yes
    immediate: yes
  with_items: "{{ znc_firewalld_zones }}"
