# @tag libvirt - setup libvirt virtualizatation toolkit

galaxy_info:
  role_name: libvirt
  author: "nodiscc <nodiscc@gmail.com>"
  description: "virtualization toolkit"
  license: "GPL-3.0"
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "10"
        - "11"
  galaxy_tags:
    - virtualization
    - libvirt
    - kvm
    - vm
    - hypervisor
dependencies:
  - nodiscc.xsrv.handlers
