- name: restart bitmagnet
  service:
    name: bitmagnet
    state: restarted
    enabled: yes
  become: yes
  when: bitmagnet_enable_service
  ignore_errors: "{{ ansible_check_mode }}"

- name: update CA certificates store
  become: yes
  command: update-ca-certificates
  changed_when: yes
