- name: restart planarally
  become: yes
  systemd:
    name: planarally.service
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"

- name: update CA certificates store
  become: yes
  command: update-ca-certificates
  changed_when: yes
