- name: include variable checks tasks
  import_tasks : checks.yml
  tags:
    - icecast
    - checks

- name: include icecast setup tasks
  import_tasks: icecast.yml
  become: yes
  tags: icecast

- name: include self-signed certificates setup tasks
  import_tasks:  ssl-selfsigned.yml
  become: yes
  tags:
    - icecast
    - ssl

- name: include apache configuration tasks
  import_tasks: apache.yml
  become: yes
  tags:
    - icecast
    - apache

- name: include manual icecast playlist reload tasks
  import_tasks: icecast-reload-playlist.yml
  tags:
    - never
    - icecast-reload-playlist
