- include: checks.yml
  tags:
    - icecast
    - checks

- include: icecast.yml
  become: yes
  tags: icecast

- include: ssl-selfsigned.yml
  become: yes
  tags:
    - icecast
    - ssl

- include: apache.yml
  become: yes
  tags:
    - icecast
    - apache

- include: icecast-reload-playlist.yml
  tags:
    - never
    - icecast-reload-playlist
