- name: include variable checks tasks
  import_tasks: checks.yml
  tags:
    - rss_bridge
    - checks

- name: load distribution-specific variables
  include_vars:
    file: "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_release }}.yml"
  tags:
    - rss_bridge
    - apache
    - utils-rss-bridge-uninstall

- name: include rss-bridge configuration tasks
  import_tasks: rss-bridge.yml
  become: yes
  tags: rss_bridge

- name: include self-signed certificates configuration tasks
  import_tasks: ssl-selfsigned.yml
  become: yes
  tags:
    - apache
    - ssl
    - rss_bridge
  when: rss_bridge_https_mode == 'selfsigned'

- name: include apache configuration tasks
  import_tasks: apache.yml
  become: yes
  tags:
    - rss_bridge
    - apache

- name: include fail2ban configuration tasks
  import_tasks: fail2ban.yml
  become: yes
  tags:
    - rss_bridge
    - fail2ban
  when:
    - ansible_local.fail2ban.ansible_managed is defined
    - ansible_local.fail2ban.ansible_managed | bool

- name: include netdata configuration tasks
  import_tasks: netdata.yml
  become: yes
  tags:
    - rss_bridge
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed | bool

- name: include ansible facts configuration tasks
  import_tasks: fact.yml
  become: yes
  tags: rss_bridge

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: rss_bridge

##### UTILITIES ####
# These tasks are tagged 'never' and will never run unless one of their tags is explicitly passed on the command line
- name: include znc uninstallation tasks
  import_tasks: utils-rss-bridge-uninstall.yml
  become: yes
  tags:
    - never
    - utils-rss-bridge-uninstall
