#!/bin/bash
#Description: output a list of thunderbird tasks not marked COMPLETED
set -o errexit
set -o nounset

tasks=$(for i in ~/.thunderbird/*/calendar-data/cache.sqlite; do
	# shellcheck disable=SC2016
    sqlite3 "$i" 'SELECT `title` FROM `cal_todos` WHERE (`ical_status` NOT LIKE "%COMPLETED%" OR `ical_status` IS NULL) ORDER BY `priority` DESC LIMIT 0, 50000;'
done | sort --unique | cut -b 1-25)

count=$(echo "$tasks" | wc -l)

if [[ "$1" = "--genmon" ]]; then
    echo "<img>/usr/share/icons/Paper/16x16/apps/office-calendar.png</img>"
    echo -e "<tool>$count tasks\n$tasks</tool>"
    echo "<click>thunderbird</click>"
else
    echo "$count tasks"
    echo "$tasks"
fi