#!/bin/bash
# Description: show SSL/TLS certificate info for a domain
# Source: https://www.netmeister.org/blog/debugging-certificate-errors.html

set -o errexit
sitecert() {
        local p=443

        if [ -n "$2" ]; then
                p=$2;
        fi
        leafcert "$1" "$p" | openssl x509 -text -noout
}

leafcert() {
        local p=443
        local chain=""

        if [ "${1}" = "full" ]; then
                chain="-showcerts"
                shift
        fi

        if [ -n "$2" ]; then
                p=$2;
        fi
        </dev/null openssl s_client "${chain}" -connect "$1:$p" 2>/dev/null | \
                awk '/-----BEGIN/,/-----END/ { print }'
}

fullchain() {
        local p=443

        if [ -n "$2" ]; then
                p=$2;
        fi
        leafcert full "$1" "$p"
}

sitecert "$@"
