#!/bin/
#Description: converts .json files generated by Shreddit to a single HTML archive
# Usage: run the script from the directory where your .json files live
outfile="export.html"
echo "writing to $outfile"
for i in *.json; do cat $i | jq ' "<code> ---- " + .link_permalink + "</code>" + .body_html'; done | sed 's/^"//' | sed 's/"$//' | sed 's/\\n/\n/g' >| "$outfile"