.PHONY: test-shellcheck # test shell script with shellcheck
test-shellcheck:
	for i in $$(find SCRIPTS/ -maxdepth 1 -type f); do \
		if grep '^#!/bin/bash' "$$i" >/dev/null; then \
		shellcheck "$$i" || exit 0 ; fi; done
