#!/bin/bash
# WIP
# Description: output a list of useful/interesting manpages
# TODO search for missing commands on manpages.debian.org
set -o errexit
set -o nounset

errors=()

while read -r name; do
	if description=$(man -f "$name" 2>/dev/null); then
		echo "$description"
	else
		export errors+=("$name")
	fi
done < manpages.list

#echo "DEBUG ${errors[*]}"

for i in ${errors[*]}; do
	url="https://manpages.debian.org/$i.en.gz"
	manpage=$(curl -L --silent "$url")
	description=$(echo "$manpage" | \
		grep -Ei --after-context=2 --max-count=1 '.SH \"?NAME' | \
		grep -Eiv "^\.('SH'|'B'|'PP'|'NM')" | sed 's/\\//g' | sed "s/$i - //g")
	echo "$i - $description"
done