- name: enable required apache modules
  command: a2enmod {{ item }}
  with_items:
    - headers
    - proxy
    - proxy_http
    - proxy_wstunnel
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"

- name: copy planarally apache virtualhost configuration
  template:
    src: etc_apache2_sites-available_planarally.conf.j2
    dest: /etc/apache2/sites-available/planarally.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload apache

- name: enable planarally apache virtualhost configuration
  command: a2ensite planarally
  args:
    creates: "/etc/apache2/sites-enabled/planarally.conf"
  notify: reload apache

- name: add a hosts file entry for the planarally server fqdn
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1	{{ planarally_fqdn }}' # noqa no-tabs
    state: present
