- name: copy rsnapshot configuration for planarally backups
  template:
    src: etc_rsnapshot.d_planarally.conf.j2
    dest: /etc/rsnapshot.d/planarally.conf
    mode: "0600"
  notify: check rsnapshot configuration
