- include: checks.yml
  tags:
    - mariadb
    - checks

- include: mariadb.yml
  become: yes
  tags:
    - mariadb

- include: netdata.yml
  become: yes
  tags:
    - mariadb
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed|bool

- include: rsyslog.yml
  become: yes
  tags:
    - mariadb
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed|bool

- include: fact.yml
  become: yes
  tags: mariadb

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: mariadb
