- include: checks.yml
  tags:
    - mariadb
    - lamp
    - checks

- include: mariadb.yml
  become: yes
  tags:
    - mariadb
    - lamp

- include: monitoring.yml
  become: yes
  tags:
    - mariadb
    - lamp
    - monitoring
  when: "'nodiscc.xsrv.monitoring' in role_names"

- include: fact.yml
  become: yes
  tags: mariadb

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: mariadb
