- name: include variable checks tasks
  import_tasks: checks.yml
  tags:
    - mariadb
    - checks

- name: include mariadb setup tasks
  import_tasks: mariadb.yml
  become: yes
  tags:
    - mariadb

- name: include netdata configuration tasks
  import_tasks: netdata.yml
  become: yes
  tags:
    - mariadb
    - monitoring
    - netdata
  when:
    - ansible_local.netdata.ansible_managed is defined
    - ansible_local.netdata.ansible_managed|bool

- name: include rsyslog configuration tasks
  import_tasks: rsyslog.yml
  become: yes
  tags:
    - mariadb
    - monitoring
    - rsyslog
  when:
    - ansible_local.rsyslog.ansible_managed is defined
    - ansible_local.rsyslog.ansible_managed|bool

- name: include ansibel facts setup tasks
  import_tasks: fact.yml
  become: yes
  tags: mariadb

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: mariadb
