##### PROXMOX HYPERVISOR #####
# firewall zones for the proxmox Web UI service, if nodiscc.xsrv.common/firewalld role is deployed
# 'zone:' is one of firewalld zones, set 'state:' to 'disabled' to remove the rule (the default is state: enabled)
proxmox_web_firewalld_zones:
  - zone: internal
    state: enabled
  - zone: internal
    state: enabled
# list of IP addresses/networks (CIDR notation) which should be allowed to access the Proxmox web interface
# set to an empty list to allow access from any IP address
proxmox_web_allow_from:
  - 192.168.0.0/16
  - 10.0.0.0/8
  - 172.16.0.0/12
