##### PROXMOX HYPERVISOR #####
# firewall zones for the proxmox Web UI service, if nodiscc.xsrv.common/firewalld role is deployed
# 'zone:' is one of firewalld zones, set 'state:' to 'disabled' to remove the rule (the default is state: enabled)
proxmox_web_firewalld_zones:
  - zone: internal
    state: enabled
  - zone: internal
    state: enabled
