# @tag znc - setup ZNC IRC bouncer
# @tag utils-znc-uninstall - (manual) uninstall ZNC IRC bounder

galaxy_info:
  role_name: znc
  author: "nodiscc <nodiscc@gmail.com>"
  description: "IRC bouncer"
  license: "GPL-3.0"
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - "11"
  galaxy_tags:
    - irc
    - bouncer
dependencies:
  - nodiscc.xsrv.handlers
