- name: install requirements
  apt:
    state: present
    package:
      - adduser
      - libfontconfig1
      - musl

- name: download grafana deb package
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_10.3.3_amd64.deb
    dest: /root/grafana_10.3.3_amd64.deb
    owner: root
    group: root
    mode: "0644"

- name: install grafana deb package
  apt:
    state: present
    deb: /root/grafana_10.3.3_amd64.deb
  ignore_errors: "{{ ansible_check_mode }}"

- name: configure grafana
  template:
    src: etc_grafana_grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: "0640"
  tags: grafana-config
  notify: restart grafana
  ignore_errors: "{{ ansible_check_mode }}"

##### SERVICE #####

- name: start/stop/enable/disable grafana service
  service:
    name: grafana-server
    state: "{{ 'started' if grafana_enable_service else 'stopped' }}"
    enabled: "{{ 'yes' if grafana_enable_service else 'no' }}"
  tags: services
  ignore_errors: "{{ ansible_check_mode }}"
