- name: copy proxmox web firewalld service definition
  template:
    src: etc_firewalld_services_proxmox-webui.xml.j2
    dest: /etc/firewalld/services/proxmox-webui.xml
    owner: root
    group: adm
    mode: 0640
  notify: reload firewalld
  ignore_errors: "{{ ansible_check_mode }}"

# reload firewalld service definitions
- name: apply configuration (flush handlers)
  meta: flush_handlers

- name: setup proxmox firewalld rules
  firewalld:
    zone: "{{ item.zone }}"
    service: proxmox-webui
    state: "{{ item.state }}"
    permanent: yes
    immediate: yes
  with_items: "{{ proxmox_web_firewalld_zones }}"
