- name: install libvirt tools
  apt:
    state: present
    package:
      - virt-manager
      - virtinst
      - virt-viewer
      - dnsmasq-base
      - libvirt-daemon-system
      - gir1.2-spiceclientgtk-3.0
      - qemu-kvm
      - qemu-utils
      - netcat-openbsd
      # - ebtables

- name: configure libvirt-guests
  template:
    src: etc_default_libvirt-guests.j2
    dest: /etc/default/libvirt-guests
    owner: root
    group: root
    mode: 0644

- name: create directory for libvirtd systemd overrides
  file:
    state: directory
    path: /etc/systemd/system/libvirtd.service.d/
    owner: root
    group: root
    mode: 0755

- name: configure libvirt systemd unit overrides
  template:
    src: etc_systemd_system_libvirtd.service.d_override.conf.j2
    dest: /etc/systemd/system/libvirtd.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify: reload systemd unit files

- name: enable libvirtd/libvirt-guests services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - libvirtd
    - libvirt-guests

- name: configure libvirt port forwards
  template:
    src: etc_libvirt_hooks_qemu.j2
    dest: /etc/libvirt/hooks/qemu
    owner: root
    group: root
    mode: 0755
  notify: restart libvirtd
  ignore_errors: "{{ ansible_check_mode }}"

- name: configure libvirt networks
  community.libvirt.virt_net:
    name: "{{ item.name }}"
    command: define
    xml: "{{ lookup('template', 'network.xml.j2' ) }}"
    autostart: "{{ item.autostart | default(True) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ libvirt_networks }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: create storage pool paths
  file:
    state: directory
    path: "{{ item.path }}"
  with_items: "{{ libvirt_storage_pools }}"
  ignore_errors: "{{ ansible_check_mode }}"

# TODO autostart does not work
# TODO activate pools after creation
- name: create storage pools
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    command: define
    xml: "{{ lookup('template', 'pool.xml.j2' ) }}"
    autostart: "{{ item.autostart | default(True) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ libvirt_storage_pools }}"
  ignore_errors: "{{ ansible_check_mode }}"

##### VMS #####

- name: create/define virtual machines
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('file', item.xml_file ) }}"
    autostart: "{{ item.autostart | default(True) }}"
  when: (item.state is not defined) or (item.state in ['present', 'running', 'destroyed', 'shutdown'])
  with_items: "{{ libvirt_vms }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: libvirt-vms

- name: list virtual machines
  community.libvirt.virt:
    command: list_vms
  register: listed_vms
  check_mode: no # always run
  ignore_errors: "{{ ansible_check_mode }}"
  tags: libvirt-vms

- name: stop VMs to be deleted
  community.libvirt.virt:
    name: "{{ item.name }}"
    state: "destroyed"
  when:
    - item.state is defined
    - item.state == "absent"
    - item.name in listed_vms.list_vms
  with_items: "{{ libvirt_vms }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: libvirt-vms

- name: delete/undefine virtual machines
  community.libvirt.virt:
    command: undefine
    name: "{{ item.name }}"
  when:
    - item.state is defined
    - item.state == "absent"
    - item.name in listed_vms.list_vms
  with_items: "{{ libvirt_vms }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: libvirt-vms

- name: start/pause/shutdown/stop libvirt VMs
  community.libvirt.virt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  when:
    - item.state is defined
    - item.state in ['running', 'destroyed', 'shutdown']
  with_items: "{{ libvirt_vms }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags: libvirt-vms
