- name: copy valheim-server firewalld service definition
  template:
    src: etc_firewalld_services_valheim-server.xml.j2
    dest: /etc/firewalld/services/valheim-server.xml
    owner: root
    group: adm
    mode: 0640
  notify: reload firewalld
  ignore_errors: "{{ ansible_check_mode }}"

# reload firewalld service definitions
- name: apply configuration (flush handlers)
  meta: flush_handlers

- name: setup valheim server firewalld rules
  firewalld:
    zone: "{{ item.zone }}"
    service: valheim-server
    state: "{{ item.state }}"
    permanent: yes
    immediate: yes
  with_items: "{{ apache_firewalld_zones }}"
