- name: include variable checks tasks
  import_tasks: checks.yml
  tags:
    - valheim_server
    - steamcmd
    - checks

- name: include steamcmd setup tasks
  import_tasks: steam.yml
  become: yes
  tags:
    - valheim_server
    - steamcmd

- name: include valheim_server setup tasks
  import_tasks: valheim-server.yml
  become: yes
  tags: valheim_server

- name: include ansible facts setup tasks
  import_tasks: fact.yml
  become: yes
  tags: valheim_server

- name: include firewalld configuration tasks
  import_tasks: firewalld.yml
  become: yes
  tags:
    - valheim_server
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed|bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: valheim_server
