- include: checks.yml
  tags:
    - valheim_server
    - steamcmd
    - checks

- include: steam.yml
  become: yes
  tags:
    - valheim_server
    - steamcmd

- include: valheim-server.yml
  become: yes
  tags: valheim_server

- include: fact.yml
  become: yes
  tags: valheim_server

- include: firewalld.yml
  become: yes
  tags:
    - valheim_server
    - firewall
  when:
    - ansible_local.firewalld.ansible_managed is defined
    - ansible_local.firewalld.ansible_managed|bool

- name: apply configuration (flush handlers)
  meta: flush_handlers
  tags: valheim_server
