# https://valheim.fandom.com/wiki/Valheim_Dedicated_Server
- name: install/update valheim server - this can take a while
  become_user: steam
  command: >
    /usr/games/steamcmd
    +@sSteamCmdForcePlatformType linux
    +login {{ steamcmd_username }} {{ steamcmd_password }}
    +force_install_dir /home/steam/valheim
    +app_update 896660 validate
    +quit
  register: update_valheim_server
  changed_when: "'downloading' in update_valheim_server.stdout"
  notify: restart valheim server


- name: install valheim-server systemd service
  template:
    src: etc_systemd_system_valheim-server.service.j2
    dest: /etc/systemd/system/valheim-server.service
    mode: 0644
  notify:
    - reload systemd unit files
    - restart valheim server

##### SERVICE

- name: start/stop/enable/disable valheim-server service
  service:
    name: valheim-server
    state: "{{ 'started' if valheim_enable_service else 'stopped' }}"
    enabled: "{{ 'yes' if valheim_enable_service else 'no' }}"
  tags: services
