- name: enable apache2 modules
  command: a2enmod {{ item }}
  with_items:
    - proxy
    - proxy_http
  args:
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  notify: reload apache

- name: copy apache2 virtualhost configuration
  template:
    src: etc_apache2_sites-available_rocketchat.conf.j2
    dest: /etc/apache2/sites-available/rocketchat.conf
    mode: 0644
  notify: reload apache

- name: enable apache2 virtualhost
  command: a2ensite rocketchat
  args:
    creates: "/etc/apache2/sites-enabled/rocketchat.conf"
  notify: restart apache
