- name: enable required apache modules
  command: a2enmod {{ item }}
  with_items:
    - headers
    - proxy
    - proxy_http
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"

- name: copy bitmagnet apache virtualhost configuration
  template:
    src: etc_apache2_sites-available_bitmagnet.conf.j2
    dest: /etc/apache2/sites-available/bitmagnet.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload apache

- name: enable bitmagnet apache virtualhost configuration
  command: a2ensite bitmagnet
  args:
    creates: "/etc/apache2/sites-enabled/bitmagnet.conf"
  notify: reload apache

- name: add a hosts file entry for the bitmagnet server fqdn
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1	{{ bitmagnet_fqdn }}' # noqa no-tabs
    state: present
