- name: install netdata checks for bitmagnet
  template:
    src: etc_netdata_go.d_httpcheck.conf.d_bitmagnet.conf.j2
    dest: /etc/netdata/go.d/httpcheck.conf.d/bitmagnet.conf
    owner: root
    group: netdata
    mode: "0640"
  notify: assemble netdata configuration
  ignore_errors: "{{ ansible_check_mode }}"
