#!/bin/bash
# Description: get a visible red/green return status for the command
# Usage: alert <command>

$@
if [[ $? == 0 ]]; then color="32"; msg="OK"; else color="31"; msg="ERROR"; fi
for line in $(seq 1 10); do echo -e "\033[01;${color}m||||||||||||||| $msg |||||||||||||||\033[01;37m"; done
