#!/bin/bash
#Description: output a list of thunderbird tasks not marked COMPLETED
set -o errexit
set -o nounset

function select_tasks() {
	dbfile="$1"
	priority="$2"
	equality='=='
	if [[ "$priority" == "NULL" ]];then equality="IS"; fi
	query="SELECT \`title\` FROM \`cal_todos\` WHERE (\`ical_status\` NOT LIKE \"%COMPLETED%\" OR \`ical_status\` IS NULL) AND (\`priority\` $equality $priority ) LIMIT 0, 50000;"
	sqlite3 "$dbfile" "$query"

}

tasks_high_priority=$(for i in ~/.thunderbird/*/calendar-data/cache.sqlite; do
    select_tasks "$i" "1"
done | sort --unique | cut -b 1-25)

tasks_low_priority=$(for i in ~/.thunderbird/*/calendar-data/cache.sqlite; do
    select_tasks "$i" "9"
done | sort --unique | cut -b 1-25)

tasks_no_priority=$(for i in ~/.thunderbird/*/calendar-data/cache.sqlite; do
    select_tasks "$i" "NULL"
done | sort --unique | cut -b 1-25)

count_high_priority=$(echo "$tasks_high_priority" | wc -l)
count_low_priority=$(echo "$tasks_low_priority" | wc -l)
count_no_priority=$(echo "$tasks_no_priority" | wc -l)
count_tasks=$(( count_no_priority + count_low_priority + count_no_priority ))

if [[ "$1" = "--genmon" ]]; then
    echo "<img>/usr/share/icons/Paper/16x16/apps/office-calendar.png</img>"
    echo -e "<tool>$count tasks\n$tasks</tool>"
    echo "<click>thunderbird</click>"
else
	echo " $count_tasks TASKS"
    echo " $count_high_priority    $count_low_priority    $count_no_priority"
    echo ""
    echo " Urgent"
    echo "$tasks_high_priority"
    echo ""
    echo " Unsorted"
    echo "$tasks_no_priority" | cut -b 1-15 | tr "\n" "\|" | fold -s -w 30 | head -n5
fi