#!/bin/bash
# Description: list all netdata alarms from hosts in an ansible inventory group
#              output is formatted for usage in conky, e.g. ${texecpi 60 netdata-alarms prod}
# Usage: netdata-alarms GROUP1,GROUP2,GROUP3,...
# Example: netdata-alarms 'dev,prod,!dektop'
set -o pipefail
set -o errexit
set -o nounset

groupnames="$1"
all_hosts=$(cd ~/playbooks/default && .venv/bin/ansible "$groupnames" --list-hosts|tail -n +2)
for i in $all_hosts; do \
shortname=$(echo "$i" | cut -d'.' -f1); \
curl --max-time 1 --silent --insecure "https://$i:19999/api/v1/alarms" | \
jq -r '. | .alarms[] | "\(.status) HOSTNAME \(.summary)"' | \
sed 's/^WARNING/${color3}▧${color}/g' | \
sed 's/^CRITICAL/${color4}▧${color}/g' | \
sed "s/HOSTNAME/$shortname/g" | \
cut -b 1-68 || echo "▧ $shortname UNREACHABLE"; \
done | sort --reverse
