#!/bin/bash
# Description: transmission script - copy .torrent file to download dir on completion
# Authors: nodiscc (nodiscc@gmail.com)
# License: Public Domain
# Doc: https://trac.transmissionbt.com/wiki/Scripts

partial_hash=$(echo -n $TR_TORRENT_HASH | cut --characters=-16)
cp ~/.config/transmission/torrents/*.$partial_hash.torrent $TR_TORRENT_DIR/
