#!/bin/bash
#Description: take a picture from the webcam, save it in home directory
# source: http://www.commandlinefu.com/commands/view/11774/press-enter-and-take-a-webcam-picture.
ffmpeg -y -r 1 -t 3 -f video4linux2 -s sxga -i /dev/video0 -vframes 1 ~/webcam-$(date +%m_%d_%Y_%H_%M).jpeg
