# list of libvirt networks
# https://docs.ansible.com/ansible/latest/collections/community/libvirt/virt_net_module.html
# https://libvirt.org/formatnetwork.html
# Example:
# libvirt_networks:
#  - name: default
#    mac_address: "52:54:00:4f:b1:01"
#    forward_dev: "eth0" # optional
#    bridge_name: "virbr2"
#    ip_address: "10.0.100.1"
#    netmask: "255.255.255.0"
#    dhcp_start: "10.0.100.128" # optional
#    dhcp_end: "10.0.100.254" # optional
#    autostart: yes # optional, yes/no, default yes
#    state: prsent # optional, active/inactive/present/absent, default present
libvirt_networks: []

# list of libvirt storage pools
# https://libvirt.org/formatstorage.html
# https://docs.ansible.com/ansible/latest/collections/community/libvirt/virt_pool_module.html
# Example:
# libvirt_storage_pools:
#  - name: pool0
#    path: /var/lib/libvirt/pools/pool0
#    mode: "0750" # optional, QUOTED, default 0750
#    owner_uid: "1003" # optional, QUOTED, default 0 (root)
#    group_gid: "64055" # optional, QUOTED, default 64055 (libvirt-qemu)
#    autostart: yes # optional, default yes
#    state: inactive # optional, active/inactive/present/absent/undefined/deleted, default active
#  - name: delete-this-pool
#    state: undefined
#  - name: delete-this-pool-and-its-contents
#    state: deleted
libvirt_storage_pools: []

# https://docs.ansible.com/ansible/latest/collections/community/libvirt/virt_module.html
# https://libvirt.org/formatdomain.html
# https://manpages.debian.org/virsh
# Example:
# libvirt_vms:
#  - name: vm01.CHANGEME.org
#    state: present # present/running/stopped/shutdown/absent, default present (absent deletes the VM)
#    autostart: yes # optional, default yes
#    xml_file: "data/libvirt/vm01.CHANGEME.org.xml" # path to XML file containing the VM definition, required when state: present/running/stopped/shutdown
#  - name: remove.this.vm
#    state: absent
libvirt_vms: []

# number of VMs to shutdown in parallel when the hypervisor is being shut down
libvirt_parallel_shutdown_number: 3

# NAT/port forwarding to libvirt VMs
# Example:
# libvirt_port_forwards:
#   - host_ip: 192.168.1.20 # forward traffic arriving on this IP address on the libvirt host
#     host_port: 443 # forward traffic arriving on this port
#     protocol: tcp # (tcp/udp) forward traffic using this protocol
#     vm_ip: 10.0.0.101 # forward traffic to this IP address
#     vm_port: 443 # forward traffic to this port
#     vm_name: vm01.CHANGEME.org # VM name (rules will be applied/removed when this VM starts/shuts down)
#     bridge: virbr1 # bridge used by the VM's libvirt network, see virsh net-dumpxml
libvirt_port_forwards: []

# list of systemd units that should be started before libvirtd starts (for example mount units)
# Example:
# libvirt_service_after:
#  - mnt-KVMSTORAGE1
#  - mnt-KVMSTORAGE2
libvirt_service_after: []
