# @tag pulseaudio - setup pulseaudio sound server

galaxy_info:
  role_name: pulseaudio
  author: "nodiscc <nodiscc@gmail.com>"
  description: "local network sound server"
  license: GPL-3.0
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - 9
        - 10
  galaxy_tags:
    - pulseaudio
    - audio
    - streaming
    - server
    - lan

dependencies: []
